version: "3"
services:
  api:
    container_name: "NESTJS"
    depends_on:
      - redis
      - postgres
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 3000:3000

  redis: 
    container_name: "REDIS"
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  postgres:
    container_name: "DATABASE"
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

volumes:
  redis:
    driver: local
  docker-nest-postgres:
